publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "rv80fr_controller"
    wait_sec_between_publish: 6

    goal_names: ["pos1", "pos2","pos3","pos4"]
    # goal_names: ["pos1"]

    pos1: 
      positions: [0.5, 1.5, 0.5, 0.5, 0.5, 0.5]
      # positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    pos2: 
      positions: [0.0, 1.5, 0.0, 0.0, 0.0, 0.0]
    pos3: 
      positions: [-0.5, 0.0, 0.0, 1.57, -0.785, 0.0]
    pos4: 
      positions: [1.0, 1.0, 0.5, 0.0, 1.0, 0.0]

    joints:
      - rv80fr_joint_1
      - rv80fr_joint_2
      - rv80fr_joint_3
      - rv80fr_joint_4
      - rv80fr_joint_5
      - rv80fr_joint_6

    check_starting_point: true
    starting_point_limits:
      rv80fr_joint_1: [-3.0,3.0] 
      rv80fr_joint_2: [-1.6,1.6]
      rv80fr_joint_3: [-1.0,1.6]
      rv80fr_joint_4: [-3.0,3.0]
      rv80fr_joint_5: [-1.6,1.6]
      rv80fr_joint_6: [-1.6,1.6]
