# Default initial positions for rv80fr's ros2_control fake system

initial_positions:
  rv80fr_joint_1: 0
  rv80fr_joint_2: 0
  rv80fr_joint_3: 0
  rv80fr_joint_4: 0
  rv80fr_joint_5: 0
  rv80fr_joint_6: 0